apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-
spec:
  params:
    - name: deployment-name
      value: pipelines-vote-api
    - name: git-url
      value: https://github.com/openshift/pipelines-vote-api.git
    - name: IMAGE
      value: quay.io/stbenji/pipelines-vote-api-vault
    - name: IMAGE_TAG
      value: "0.1.0"
    - name: vault-key
      value: hashivault://cosign
  pipelineRef:
    name: image-build
  taskRunTemplate:
    serviceAccountName: pipeline-sa
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: build
