apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: cluster-app
  sources:
  - chart: kyverno
    repoURL: "https://kyverno.github.io/kyverno"
    targetRevision: 3.1.4
    helm:
      valueFiles:
        - $val/kyverno/values.yaml
  - repoURL: "git@github.com:StinkyBenji/secure-the-chain.git"
    targetRevision: main
    ref: val
  ignoreDifferences:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    jsonPointers:
      - /rules
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
