apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhtas
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-app
  source:
    repoURL: git@github.com:StinkyBenji/secure-the-chain.git
    path: trusted-artifact-signer/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true