apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhtas
  namespace: openshift-gitops
spec:
  destination:
    namespace: trusted-artifact-signer
    server: https://kubernetes.default.svc
  project: cluster-app
  sources:
  - repoURL: https://github.com/StinkyBenji/secure-the-chain.git
    path: trusted-artifact-signer/operator
  - repoURL: https://github.com/StinkyBenji/secure-the-chain.git
    path: trusted-artifact-signer/instance/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      