apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-options: 'SkipDryRunOnMissingResource=true,ServerSideApply=true'
  name: spire-crd
  namespace: openshift-gitops
spec:
  destination:
    namespace: spire-server
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: charts/spire-crds
    repoURL: 'https://github.com/spiffe/helm-charts-hardened'
    targetRevision: spire-0.20.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
      limit: -1
