apiVersion: rhtas.redhat.com/v1alpha1
kind: Securesign
metadata:
  name: securesign
  finalizers:
    - tas.rhtas.redhat.com
  labels:
    app.kubernetes.io/instance: securesign
    app.kubernetes.io/name: securesign
    app.kubernetes.io/part-of: trusted-artifact-signer
spec:
  ctlog: {}
  rekor:
    backFillRedis:
      enabled: true
      schedule: 0 0 * * *
    externalAccess:
      enabled: true
    monitoring:
      enabled: false
    pvc:
      retain: true
      size: 5Gi
    rekorSearchUI:
      enabled: true
    signer:
      kms: secret
  trillian:
    database:
      create: true
      pvc:
        retain: true
        size: 5Gi
  tuf:
    externalAccess:
      enabled: true
    keys:
      - name: rekor.pub
      - name: ctfe.pub
      - name: fulcio_v1.crt.pem
    port: 80
