apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  pipeline:
    enable-cel-in-whenexpression: true
  chain:
    artifacts.oci.storage: "oci"
    artifacts.pipelinerun.storage: "oci"
    artifacts.taskrun.signer: x509
    artifacts.pipelinerun.signer: x509
    signers.x509.fulcio.address: $FULCIO_URL
    signers.x509.fulcio.enabled: true
    signers.x509.fulcio.issuer: $SPIFFE_OIDC_URL
    signers.x509.fulcio.provider: spiffe
    signers.x509.tuf.mirror.url: $TUF_URL
    transparency.enabled: "true"
    transparency.url: $REKOR_URL
    options:
      disabled: false
      deployments:
        tekton-chains-controller:
          spec:
            template:
              spec:
                containers:
                  - name: tekton-chains-controller
                    env:
                      - name: SPIFFE_ENDPOINT_SOCKET
                        value: /spiffe-workload-api/spire-agent.sock
                      - name: TUF_ROOT
                        value: /tuf
                    resources: {}
                    volumeMounts:
                      - mountPath: /spiffe-workload-api
                        name: spiffe-workload-api
                      - mountPath: /tuf
                        name: tuf
                volumes:
                  - emptyDir: {}
                    name: tuf
                  - csi:
                      driver: csi.spiffe.io
                      readOnly: true
                    name: spiffe-workload-api
  targetNamespace: openshift-pipelines
  