apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  pipeline:
    enable-cel-in-whenexpression: true
  chain:
    artifacts.oci.storage: "oci"
    artifacts.pipelinerun.format: "slsa/v1"
    artifacts.pipelinerun.storage: "oci"
    artifacts.taskrun.format: "slsa/v1"
    artifacts.taskrun.signer: kms
    artifacts.pipelinerun.signer: kms
    artifacts.oci.signer: kms
    transparency.enabled: "true"
    signers.kms.kmsref: hashivault://cosign
    signers.kms.auth.address: <vault-addr>
    signers.kms.auth.token: <vault-token>
    options:
      disabled: false
  targetNamespace: openshift-pipelines
