apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: image-build
spec:
  params:
  - description: name of the deployment to be patched
    name: deployment-name
    type: string
  - description: url of the git repo for the code of deployment
    name: git-url
    type: string
  - default: pipelines-1.8
    description: revision to be used from repo of the code for deployment
    name: git-revision
    type: string
  - description: image to be build from the code
    name: IMAGE
    type: string
  - default: latest
    description: image tag to be build from the code
    name: IMAGE_TAG
    type: string
  - name: vault-key
    type: string
  results:
  - description: the image url
    name: IMAGE_URL
    value: $(tasks.build-image.results.IMAGE_URL)
  - description: the image digest
    name: IMAGE_DIGEST
    value: $(tasks.build-image.results.IMAGE_DIGEST)
  tasks:
  - name: fetch-repository
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace

  - name: build-image
    params:
    - name: IMAGE
      value: $(params.IMAGE):$(params.IMAGE_TAG)
    runAfter:
    - fetch-repository
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: shared-workspace

  - name: create-sbom
    params:
    - name: SYFT_ARGS
      value:
      - scan
      - registry:$(params.IMAGE)@$(tasks.build-image.results.IMAGE_DIGEST)
      - -o
      - spdx-json=/attestation_tmp/attestation.sbom
    - name: COSIGN_SCRIPT
      value: "cosign attest -y --key=$(params.vault-key) --predicate /attestation_tmp/attestation.sbom --type spdxjson $(params.IMAGE)@$(tasks.build-image.results.IMAGE_DIGEST) --attachment-tag-prefix sbom- "
    retries: 5
    runAfter:
    - build-image
    taskRef:
      kind: Task
      name: syft
  
  - name: create-vulnerability-attestation
    params:
    - name: GRYPE_ARGS
      value:
      - registry:$(params.IMAGE)@$(tasks.build-image.results.IMAGE_DIGEST)
      - --file
      - /attestation_tmp/attestation.sarif
      - -o
      - sarif
    - name: COSIGN_SCRIPT
      value: "cosign attest -y --key=$(params.vault-key) --predicate /attestation_tmp/attestation.sarif --type vuln $(params.IMAGE)@$(tasks.build-image.results.IMAGE_DIGEST) --attachment-tag-prefix sarif- "
    retries: 5
    runAfter:
    - create-sbom
    taskRef:
      kind: Task
      name: grype

  workspaces:
  - name: shared-workspace
