apiVersion: rhtas.redhat.com/v1alpha1
kind: Securesign
metadata:
  name: securesign
  namespace: openshift-operators
  finalizers:
    - tas.rhtas.redhat.com
  labels:
    app.kubernetes.io/instance: securesign
    app.kubernetes.io/name: securesign
    app.kubernetes.io/part-of: trusted-artifact-signer
spec:
  analytics: true
  ctlog: {}
  fulcio:
    certificate:
      commonName: apps.ocp4.whatever.out-of-my-head.de
      organizationEmail: rzh@redhat.com
      organizationName: Red Hat
    config:
      OIDCIssuers:
        - ClientID: trusted-artifact-signer
          Issuer: 'https://oidc-discovery.apps.ocp4.whatever.out-of-my-head.de'
          IssuerURL: 'https://oidc-discovery.apps.ocp4.whatever.out-of-my-head.de'
          Type: spiffe
          SPIFFETrustDomain: apps.ocp4.whatever.out-of-my-head.de
    externalAccess:
      enabled: true
    monitoring:
      enabled: false
  rekor:
    backFillRedis:
      enabled: true
      schedule: 0 0 * * *
    externalAccess:
      enabled: true
    monitoring:
      enabled: false
    pvc:
      retain: true
      size: 5Gi
    rekorSearchUI:
      enabled: false
    signer:
      kms: secret
  trillian:
    database:
      create: true
      pvc:
        retain: true
        size: 5Gi
  tuf:
    externalAccess:
      enabled: true
    keys:
      - name: rekor.pub
      - name: ctfe.pub
      - name: fulcio_v1.crt.pem
    port: 80
