apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/categories: Security
    tekton.dev/displayName: grype
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: linux/amd64,linux/arm64
    tekton.dev/tags: CLI, grype
  name: grype
spec:
  description: Task and library for scanning a SBOM and and creating an attestation
  params:
    - description: The Arguments to be passed to Syft command.
      name: GRYPE_ARGS
      type: array
    - description: The Arguments to be passed to cosign command.
      name: COSIGN_SCRIPT
      type: string
    - default: docker.io/anchore/grype:v0.56.0
      description: Grype image to be used
      name: GRYPE_IMAGE
      type: string
    - default: bitnami/cosign:latest
      description: Cosing image to be used
      name: COSIGN_IMAGE
      type: string
    - default: VAULT_ADDR
      description: The secret key for hashicorp vault address
      name: vault-addr-key
      type: string
    - default: VAULT_TOKEN
      description: The secret key for hashicorp vault token
      name: vault-token-key
      type: string
    - default: vault-secret
      description: Cosing image to be used
      name: vault-secret-name
      type: string
  steps:
    - args:
        - $(params.GRYPE_ARGS)
      env:
        - name: GRYPE_DB_CACHE_DIR
          value: /tmp/.cache
      image: $(params.GRYPE_IMAGE)
      name: grype
      volumeMounts:
        - mountPath: /attestation_tmp
          name: tmp
      workingDir: $(workspaces.source-dir.path)
    - args:
        - -c
        - $(params.COSIGN_SCRIPT)
      command:
        - /bin/bash
      image: $(params.COSIGN_IMAGE)
      name: cosign
      env:
        - name: VAULT_ADDR
          valueFrom:
            secretKeyRef:
              key: $(params.vault-addr-key)
              name: $(params.vault-secret-name)
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              key: $(params.vault-token-key)
              name: $(params.vault-secret-name)
      volumeMounts:
        - mountPath: /attestation_tmp
          name: tmp
  volumes:
    - name: tmp
  workspaces:
    - name: source-dir
      optional: true
